---

- name: Habilitando Servicios
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  become: yes
  with_items:
    - "nfs-server"

- name: Creacion de fichero exports
  file: 
    path: /etc/exports
    state: touch

- name: Escritura en fichero exports de las ip de los nodos
  lineinfile: 
    path: /etc/exports
    line: '/mnt/srv/nfs "{{ item.line }}"(rw,sync)'      
  with_items:
    - { vm: 'master', line: '{{ master_private_ip }}'}
    - { vm: 'worker01', line: '{{ worker01_private_ip }}'}

- name: Recargando configuracion de servico nfs
  shell: systemctl reload nfs;exportfs -a;exportfs -r;exportfs -s