---
- name: Modificacion del fichero /etc/hosts
  blockinfile: 
    path: /etc/hosts 
    state: present
    block: |
      {{ master_private_ip }}  master.eqs-sdg.com
      {{ worker01_private_ip }}  worker01.eqs-sdg.com
    insertafter: EOF
    marker: "## {mark} DNS Servers"

- name: Cargamos el modulo br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: configuramos net.bridge.bridge-nf-call-ip6tables a 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present

- name: configuramos net.bridge.bridge-nf-call-iptables a 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present

- name: Desactivamos SWAP 
  shell: |
    swapoff -a

- name: Desactivamos SWAP en fstab 
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent

- name: Instalamos paquetes necesarios
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Añadimos GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Añadimos repositorio docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Instalamos docker
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Instalamos modulo de docker para pyhton
  pip:
    name: docker

- name: Arrancamos Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Download apt key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /tmp # or /etc/pki/rpm-gpg depending on the infrastructure

- name: Add a key from a file
  ansible.builtin.apt_key:
    file: /tmp/apt-key.gpg
    state: present

- name: add Kubernetes APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'
    update_cache: true

- name: Instalamos kubernetes (kubelet) 
  apt:
    name: kubelet
    state: present
    update_cache: true

- name: Instalamos kubernetes (kubeadm)
  apt:
    name: kubeadm
    state: present

- name: Instalamos kubernetes (kubectl)
  apt:
    name: kubectl
    state: present

