---

- name: Configurar Zona horaria
  timezone:
    name: Europe/Madrid 
  become: yes

- name: Actualizando repos y cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Instalando prerequisitos
  apt:
    name: "{{ services_init }}"
    state: present
  become: yes