---

- name: configurando puertos
  firewalld:
    port: "{{ item }}"
    permanent: 'true'
    immediate: yes
    state: enabled
  with_items:
    - "6443/tcp"
    - "2379-2380/tcp"
    - "10250-10252/tcp"
    - "10255/tcp"

- name: Permitiremos el acceso desde los workers y desde el propio master
  firewalld:
    rich_rule: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - "rule family=ipv4 source address={{ worker01_private_ip }}/24 accept"

- name: Permitimos el acceso de los contenedores a localhost
  firewalld:
    zone: public
    rich_rule: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - "rule family=ipv4 source address=172.17.0.1/16 accept"

#SDN Azure
- name: configurando puertos SDN
  firewalld:
    port: "{{ item }}"
    permanent: 'true'
    immediate: yes
    state: enabled
  with_items:
    - "8285/udp"
    - "8472/udp"


