---

- hosts: all
  vars_files:
    - "group_vars/kubernetes.yaml"
    - "group_vars/services.yaml"
  gather_facts: true
  become: yes
  roles:
    - prerequisites

- hosts: all
  vars_files:
    - "group_vars/kubernetes.yaml"
    - "group_vars/services.yaml"
  gather_facts: true
  become: yes
  roles:
    - common

- hosts: master
  vars_files:
    - "group_vars/kubernetes.yaml"
    - "group_vars/services.yaml"
  gather_facts: true
  become: yes
  roles:
    - master

- hosts: workers
  vars_files:
    - "group_vars/kubernetes.yaml"
    - "group_vars/services.yaml"
  gather_facts: true
  become: yes
  roles:
    - workers

